@extends('layouts.app')
@section('title', 'Timetable Generator')
@section('content')
<div class="timetable-page">
    <section class="generator-hero mb-4"><div class="row align-items-center g-4"><div class="col-lg-8"><span class="eyebrow"><i class="bi bi-stars"></i> Academic scheduling workspace</span><h1 class="display-6 fw-bold mt-3 mb-2">Generate an international-standard teaching timetable</h1><p class="lead mb-0">The engine checks instructor availability, room capacity, venue clashes, instructor clashes, and program-year cohort clashes.</p></div><div class="col-lg-4"><form action="{{ route('timetable.generate') }}" method="POST" id="generate-form">@csrf<button class="btn btn-light btn-lg w-100 generator-button" @disabled(!$isReady)><span class="button-idle"><i class="bi bi-cpu-fill me-2"></i>Generate timetable</span><span class="button-loading d-none"><span class="spinner-border spinner-border-sm me-2"></span>Optimizing…</span></button></form><small class="d-block mt-2 text-center text-white-50">{{ $isReady ? 'All scheduling inputs are ready.' : 'Complete missing assignments before generation.' }}</small></div></div></section>

    <section class="row g-3 mb-4" aria-label="Scheduling readiness">
        @foreach([['Courses',$counts['courses'],'bi-book','courses'],['Instructors',$counts['instructors'],'bi-person-badge','instructors'],['Venues',$counts['venues'],'bi-building','venues'],['Time slots',$counts['timeSlots'],'bi-clock-history','availability']] as [$label,$count,$icon,$route])
        <div class="col-6 col-xl-3"><a class="readiness-card {{ $count ? 'is-ready':'needs-data' }}" href="{{ route($route) }}"><span class="readiness-icon"><i class="bi {{ $icon }}"></i></span><span><strong>{{ $count }}</strong><small>{{ $label }}</small></span><i class="bi {{ $count ? 'bi-check-circle-fill':'bi-exclamation-circle-fill' }} status-icon"></i></a></div>
        @endforeach
        @if($unassignedCourses)<div class="col-12"><div class="alert alert-warning border-0"><i class="bi bi-exclamation-triangle me-2"></i><strong>{{ $unassignedCourses }} course(s)</strong> still need an instructor or year assignment. Add new complete assignments from Courses before generation.</div></div>@endif
    </section>

    @if(isset($schedule))
    <section class="result-summary mb-4"><div class="d-flex flex-column flex-lg-row align-items-lg-center justify-content-between gap-3"><div><span class="result-kicker"><i class="bi bi-check-circle-fill"></i> Generation complete</span><h2 class="h4 fw-bold mb-1">Master teaching timetable</h2><p class="text-muted mb-0">{{ $schedule->count() }} teaching sessions generated in {{ $duration }} seconds.</p></div><div class="summary-metrics"><div><strong>{{ $fitness }}%</strong><span>Fitness</span></div><div><strong>{{ $conflicts }}</strong><span>Conflicts</span></div><div><strong>{{ $generation }}</strong><span>Generations</span></div></div></div></section>

    <section class="schedule-panel">
        <div class="schedule-toolbar"><div><h2 class="h5 fw-bold mb-1"><i class="bi bi-calendar3 text-primary me-2"></i>Weekly schedule</h2><p class="small text-muted mb-0" id="result-count">Showing {{ $schedule->count() }} sessions</p></div><div class="toolbar-actions"><div class="search-box"><i class="bi bi-search"></i><input id="schedule-search" class="form-control" placeholder="Search code, surname or venue"></div><select id="year-filter" class="form-select"><option value="">All years</option>@foreach($years as $year)<option value="{{ $year }}">Year {{ $year }}</option>@endforeach</select><button class="btn btn-outline-primary" onclick="window.print()"><i class="bi bi-printer me-1"></i>Print</button></div></div>
        <div class="table-responsive"><table class="table schedule-table align-middle mb-0"><thead><tr><th>Day</th><th>Time to be taught</th><th>Course code</th><th>Instructor surname</th><th>Venue</th><th>Year</th></tr></thead><tbody id="schedule-body">
            @foreach($schedule as $item)<tr data-year="{{ $item['year_of_study'] }}" data-search="{{ Str::lower($item['course_code'].' '.$item['instructor_surname'].' '.$item['venue_name'].' '.$item['day'].' '.$item['time_slot']) }}"><td><span class="day-pill">{{ $item['day'] }}</span></td><td><span class="time-value"><i class="bi bi-clock"></i> {{ $item['time_slot'] }}</span></td><td><strong class="course-code">{{ $item['course_code'] }}</strong></td><td>{{ $item['instructor_surname'] }}</td><td><span class="cell-detail"><i class="bi bi-geo-alt"></i>{{ $item['venue_name'] }}</span></td><td><span class="year-badge">Year {{ $item['year_of_study'] }}</span></td></tr>@endforeach
            <tr id="empty-filter-state" class="d-none"><td colspan="6" class="text-center py-5 text-muted">No sessions match the selected filters.</td></tr>
        </tbody></table></div>
    </section>
    @else<section class="empty-schedule text-center"><span class="empty-icon"><i class="bi bi-calendar2-week"></i></span><h2 class="h4 fw-bold mt-3">No timetable generated yet</h2><p class="text-muted mx-auto">Complete the readiness requirements, then generate the master timetable.</p></section>@endif
</div>
@push('scripts')<script>
document.getElementById('generate-form')?.addEventListener('submit',function(){const b=this.querySelector('button');b.disabled=true;b.querySelector('.button-idle').classList.add('d-none');b.querySelector('.button-loading').classList.remove('d-none');});
const search=document.getElementById('schedule-search'),year=document.getElementById('year-filter'),rows=[...document.querySelectorAll('#schedule-body tr[data-year]')];function filter(){const q=(search?.value||'').toLowerCase(),y=year?.value||'';let n=0;rows.forEach(r=>{const show=(!y||r.dataset.year===y)&&(!q||r.dataset.search.includes(q));r.classList.toggle('d-none',!show);if(show)n++;});document.getElementById('empty-filter-state')?.classList.toggle('d-none',n!==0);if(document.getElementById('result-count'))document.getElementById('result-count').textContent=`Showing ${n} of ${rows.length} sessions`;};search?.addEventListener('input',filter);year?.addEventListener('change',filter);
</script>@endpush
@endsection
